# Generated by Django 4.1.4 on 2023-01-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repas',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
