# Generated by Django 4.1.4 on 2023-01-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_du_menu', models.CharField(max_length=50)),
                ('liste_des_plats', models.ManyToManyField(to='app.repas')),
            ],
        ),
    ]
